### ISSUE TITLE
Crash when clicking "Save and Quit to Title"

### ISSUE THREAD

**Issue by YumatanGames** [Pandarix/BetterArcheology#17] opened 2023-06-19 02:40 UTC
Hey, I've run into an issue with the game crashing when I try to go back to the main menu via "Save and Quit to Title".

The crash seems to be tied to the BetterArcheology mod, or potentially its interaction with other mods. I've only noticed the crash when this mod is active, and haven't experienced crashes with it under any other circumstances.

I'm not sure if the issue is with the mod itself or some odd interaction with another mod, as I haven't done an isolated test with just Better Archeology.

Here's the modlist in case it's helpful:

  [✔] AdditionalStructures-1.20.x-(v.4.2.0)
  [✔] advancednetherite-fabric-2.0.2-1.20
  [✔] adventurez-1.4.18
  [✔] alloy-forgery-2.0.21+1.20
  [✔] alternate-current-mc1.20-1.6.0
  [✔] AmbientSounds_FABRIC_v5.2.19_mc1.20
  [✔] amecs-1.3.9+mc.1.20-pre2
  [✔] animal_feeding_trough-1.0.3+1.20
  [✔] appleskin-fabric-mc1.20-2.5.0
  [✔] ArchaeologyBanners-Fabric-1.20-4.0.1
  [✔] archeologyplus-1.0.1
  [✔] architectury-9.0.8-fabric
  [✔] areas-1.20.0-4.4
  [✔] azurelib-fabric-1.20-1.0.14
  [✔] badpackets-fabric-0.4.1
  [✔] balm-fabric-1.20-7.0.3
  [✔] bclib-3.0.7
  [✔] BetterAnimationsCollection-v7.0.0-1.20-Fabric
  [✔] betterarcheology-1.0.1
  [✔] better-enchanted-books-1.20-1.4.3
  [✔] better-end-4.0.3
  [✔] better-nether-9.0.5
  [✔] betterthanmending-1.3.0
  [✔] BetterTridents-v7.0.0-1.20-Fabric
  [✔] biomemakeover-FABRIC-1.20.0-1.10.0
  [✔] Bookshelf-Fabric-1.20-19.0.15
  [✔] brrp-fabric-1.0.0-1.20.1
  [✔] bsvsb-3.0.3
  [✔] c2me-fabric-mc1.20-0.2.0+alpha.10.88
  [✔] capes-1.5.2+1.20-fabric
  [✔] cem-0.8.0
  [✔] cherishedworlds-fabric-6.1.0+1.20.1
  [✔] CITResewn-1.1.3+1.20
  [✔] CleanF3-0.4.0-mc1.20
  [✔] cloth-config-11.0.99-fabric
  [✔] Clumps-fabric-1.20-11.0.0.1
  [✔] collective-1.20.0-6.57
  [✔] comforts-fabric-6.3.2+1.20.1
  [✔] completeconfig-2.4.0
  [✔] CreativeCore_FABRIC_v2.10.23_mc1.20
  [✔] cristellib-1.1.0
  [✔] ctov-3.3.0
  [✔] CullLessLeaves-1.2.0
  [✔] dark-loading-screen-1.6.14
  [✔] dashloader-5.0.0-beta.1+1.20.0
  [✔] deathlog-0.3.2+1.20
  [✔] Debugify-1.20+1.1
  [✔] DiagonalFences-v7.0.0-1.20-Fabric
  [✔] do-a-barrel-roll-3.0.1+1.20-fabric
  [✔] DripSounds-1.19.4-0.3.2
  [✔] dungeons-and-taverns-v2.1.3
  [✔] dynamic-fps-2.3.0
  [✔] earth2java-fabric-1.10.1+1.20
  [✔] EasyAnvils-v7.0.0-1.20-Fabric
  [✔] EasyMagic-v7.0.0-1.20-Fabric
  [✔] EasyShulkerBoxes-v7.0.0-1.20-Fabric
  [✔] emi-1.0.3+1.20+fabric
  [✔] EnchantingInfuser-v7.0.0-1.20-Fabric
  [✔] enchantment-lore-1.3.2+MC1.20-1.20.1
  [✔] Essential-fabric_1-19
  [✔] fabric-api-0.83.0+1.20
  [✔] fabric-language-kotlin-1.9.5+kotlin.1.8.22
  [✔] ferritecore-6.0.0-fabric
  [✔] fish_of_thieves-mc1.20-v3.0.0-fabric
  [✔] ForgeConfigAPIPort-v7.0.0-1.20-Fabric
  [✔] ForgeConfigScreens-v7.0.0-1.20-Fabric
  [✔] freecam-fabric-modrinth-1.2.0+1.20
  [✔] friendsandfoes-fabric-mc1.20-1.9.0
  [✔] Gamma-Utils-1.7.15-mc1.20.1
  [✔] geckolib-fabric-1.20-4.2
  [✔] graves-3.0.0-beta.2+1.20
  [✔] icarus-1.16
  [✔] IllagersWearArmor-1.1.0+1.20
  [✔] ImmediatelyFast-1.1.15+1.20.1
  [✔] immersive_aircraft-0.5.1+1.20-fabric
  [✔] immersive_paintings-0.6.1+1.20-fabric
  [✔] imst-2.1.0
  [✔] indium-1.0.18+mc1.20
  [✔] iris-mc1.20-1.6.4
  [✔] Jade-1.20-fabric-11.1.3
  [✔] krypton-0.2.3
  [✔] LeaveMyBarsAlone-v7.0.0-1.20-Fabric
  [✔] LeavesBeGone-v7.0.0-1.20-Fabric
  [✔] letmedespawn-fabric-1.20-1.1.0
  [✔] lithium-fabric-mc1.20-0.11.2
  [✔] lunade-fastanim-1.6-1.20
  [✔] mavapi-1.1.0-mc1.20
  [✔] mavm-1.2.3-mc1.20
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] minecraft-comes-alive-7.5.3+1.20-universal
  [✔] mixintrace-1.1.1+1.17
  [✔] mob-captains-v2.1.2
  [✔] modernfix-fabric-5.0.2+mc1.20
  [✔] modmenu-7.0.1
  [✔] moonlight-1.20-2.5.6-fabric
  [✔] mooshroomtweaks-1.20.0-3.2
  [✔] MoreBows-1.0.11+1.20.x
  [✔] morediscs-1.20-28-fabric
  [✔] moremobvariants-fabric+1.20-1.2.2
  [✔] mousewheelie-1.11.1+mc1.20-pre2
  [✔] netherportalfix-fabric-1.20-13.0.0
  [✔] OverpoweredMending-1.20-2.11.0
  [✔] owo-lib-0.11.0+1.20
  [✔] Philips-Ruins1.20-1.1[Fabric]
  [✔] PickUpNotifier-v7.0.0-1.20-Fabric
  [✔] pinglist-1.4
  [✔] PresenceFootsteps-1.9.0
  [✔] puzzle-1.5.1+1.20
  [✔] PuzzlesLib-v7.0.3-1.20-Fabric
  [✔] randomvillagenames-1.20.0-3.3
  [✔] reacharound+1.20-1.1.2
  [✔] reeses_sodium_options-1.5.1+mc1.20-build.74
  [✔] RegionsUnexploredFabric-0.4.1+1.20
  [✔] reinforced-barrels-2.4.1+1.20
  [✔] reinforced-chests-2.4.2+1.20
  [✔] reinforced-shulker-boxes-2.4.1+1.20
  [✔] repurposed_structures-7.0.0+1.20-fabric
  [✔] servercore-fabric-1.3.6+1.20
  [✔] sodium-extra-0.4.20+mc1.20-build.103
  [✔] sodium-fabric-mc1.20-0.4.10+build.27
  [✔] soundphysics-fabric-1.20-1.1.1
  [✔] spyglass_astronomy-1.0.5-mc1.20+
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] supplementaries-1.20-2.5.6-fabric
  [✔] symbol-chat-1.20-1.0.0
  [✔] TaxFreeLevels-1.3.3-fabric-1.19
  [✔] tectonic-mod-mc1.20-v2
  [✔] TerraBlender-fabric-1.20-3.0.0.163
  [✔] The_Graveyard_2.9.1_(FABRIC)_1.20+
  [✔] tooltipfix-1.1.1-1.20
  [✔] Towns-and-Towers-1.11-Fabric+Forge
  [✔] TradingPost-v7.0.0-1.20-Fabric
  [✔] travelers-backpack-1.20-9.0.2
  [✔] treeharvester-1.20.0-8.1
  [✔] trinkets-3.7.0
  [✔] veinmining-fabric-1.2.0+1.20.1
  [✔] villagernames-1.20-4.5.1
  [✔] VisualWorkbench-v7.0.0-1.20-Fabric
  [✔] Void-Fog-2.10.0
  [✔] waystones-fabric-1.20-14.0.0
  [✔] WilderWild-2.0.4-Fabric+1.20
  [✔] windchimes-1.2.3+1.20
  [✔] wthit-fabric-8.1.0
  [✔] Xaeros_Minimap_23.5.0_Fabric_1.20
  [✔] XaerosWorldMap_1.30.6_Fabric_1.20
  [✔] yet-another-config-lib-fabric-3.0.1+1.20
  [✔] Zoomify-2.10.0
  
Any help sorting this out would be super appreciated!
Love the mod, btw! :D
Cheers!
  1
[crash-2023-06-18_20.38.56-client.txt](https://github.com/Pandarix/BetterArcheology/files/11783549/crash-2023-06-18_20.38.56-client.txt)

**Comment by Pandarix** [comment] 2023-06-19 11:11
That sounds bad, I'll look into it asap.
First I'll try replicating this issue, I'll send some updates :)

**Comment by Pandarix** [comment] 2023-06-19 11:23
Quick question @YumatanGames, is it possible that you've placed a VillagerFossil and given it an Item? If so, what Item was it?
I'm currently trying to point my finger at something and that would be my first guess.

**Comment by Pandarix** [comment] 2023-06-19 11:26
The Error says:

> Cannot invoke "net.minecraft.class_2248.method_8389()" because the return value of "net.mehvahdjukaar.moonlight.api.set.wood.WoodType.getBlockOfThis(String)" is null

As far as I know `net.minecraft.class_2248` corresponds to `Block` and `.method_8389()` to `asItem()`
(see https://maven.fabricmc.net/docs/yarn-21w15a+build.2/net/minecraft/block/Block.html)

**Comment by Pandarix** [comment] 2023-06-19 11:29
I've managed to recreate the issue, which seems to be with either with `Supplementaries `or its dependency `Moonlight Lib`

**Comment by Pandarix** [comment] 2023-06-19 12:01
It actually is an error of Supplementaries itself. Please download the newest version of Supplementaries directly from CurseForge or update it in the launcher if possible.

BetterArcheology introduces a new WoodType but no HangingSign which clashed with Supplementaries' behaviour. A lot of mods do that, and they had to fix that themselves.

So download [this File](https://legacy.curseforge.com/minecraft/mc-mods/supplementaries/download/4596013) or just search for a version that has this in its changelog:

> - fixed an issue with creative tabs not accounting for mods that didnt add a hanging sign for their wood

Hope you'll keep enjoying the mod!
Cheers, I'll close this for now ;)
If something else pops up, feel free to open a new issue.

**Closed as completed by Pandarix** 2023-06-19 12:01 UTC
Labels: invalid

**Comment by YumatanGames** [comment] 2023-06-19 13:18
Oh, I love this mod! It's so well thought out and well done! I love the art style too! Thank you very much for looking into this. For some reason, I thought it could be Supplementaries... They also clash with a mod of mine, Dimensional Anchor. 

Any way, I really appreciate you taking your time to find a Supplementaries version that works with the pack I'm building. :D

**Comment by Pandarix** [comment] 2023-06-19 14:56
Thank you so much! :D
No problem, I'm just glad the issue is solved ^^.
Ooo, can you send me a link to your profile? I'd love to take a look :)

**Comment by YumatanGames** [comment] 2023-06-20 07:07
Of course. Here it is:
https://legacy.curseforge.com/members/YumatanGames/projects
